#### general settings
name: DANx4
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
pca_matrix_path: ../../../pca_aniso_matrix_x4.pth # ../../../pca_aniso_matrix_x2.pth when scale=2

degradation:
  random_kernel: True
  ksize: 21 # 11 when scale=2
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true

#### datasets
datasets:
  train:
    name: DIV2K
    mode: GT
    dataroot_GT: /data/DIV2K_Flickr2K/x4HR.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 64
    GT_size: 256
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2KRK
    mode: LQGT
    dataroot_GT: /data/DIV2KRK_public/HRblur.lmdb
    dataroot_LQ: /data/DIV2KRK_public/x4LRblur.lmdb

#### network structures
network_G:
  which_model_G: DAN
  setting:
    nf: 64
    nb: 40
    input_para: 10
    loop: 4
    upscale: 4
    kernel_size: 21
    pca_matrix_path: ../../../pca_aniso_matrix_x4.pth # ../../../pca_aniso_matrix_x2.pth when scale=2

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [200000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2.5e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2.5e3
